
const entityLabels = {
  contact: {
    phone:          'Номер телефона',
    name:           'Имя водителя',
    series:         'Серия',
    number:         'Номер',
    issueDate:      'Дата выдачи',
    issuedBy:       'Выдал',
    code:           'Код',
    TipTS:          'Тип ТС',
    markaAvto:      'Марка авто',
    gosNomer:       'г/н',
    TipPricepa:     'п/прицеп',
    pp:             'г/н пп',
  },
  company: {
    customer_org_type:       'Тип организации (полный)',
    customer_org_type_short: 'Тип организации (короткий)',
    inn:                     'ИНН',
    name:                    'Название',
    contactPerson:           'ФИО',
    position:                'Должность',
    kpp:                     'КПП',
    company_phone:           'Номер телефона',
    ogrn:                    'ОГРН',
    ogrnip:                  'ОГРНИП',
    bic:                     'БИК',
    bank:                    'Банк',
    ks:                      'к/с',
    rs:                      'р/с',
    postalСode:              'Почтовый индекс',
    city:                    'Город',
    street:                  'Улица',
    building:                'Дом',
    office:                  'Офис',
    emailcompani:            'Электронная почта',
  },
  carrier: {
    customer_org_type:       'Тип организации (полный)',
    customer_org_type_short: 'Тип организации (короткий)',
    carrier_inn:             'ИНН',
    carrier_name:            'Название',
    carrier_contactPerson:   'ФИО',
    carrier_position:        'Должность',
    carrier_kpp:             'КПП',
    carrier_company_phone:   'Номер телефона',
    carrier_ogrn:            'ОГРН',
    carrier_ogrnip:          'ОГРНИП',
    carrier_bic:             'БИК',
    carrier_bank:            'Банк',
    carrier_ks:              'к/с',
    carrier_rs:              'р/с',
    carrier_postalCode:      'Почтовый индекс',
    carrier_city:            'Город',
    carrier_street:          'Улица',
    carrier_building:        'Дом',
    carrier_office:          'Офис',
    carrier_emailcompani:    'Электронная почта',
  }
};


export default entityLabels;